### ISSUE TITLE
Table 1中的数据问题

### ISSUE THREAD

**Issue by moothes** [zhuye98/ICL#1]
您好，感谢您分享这个有趣的工作。
但是在论文的Table 1的第一列中，您标记的是3 cases和14 cases，但是在论文的表述中好像是3 cases和7 cases。
想问一下这里正确的标注应该是什么？是否是标记错误？

**Comment by zhuye98** [comment]
你好，感谢指出这个问题。第一列正确的标注是3 cases和7 cases，我会在之后的版本做出更正。
