### ISSUE TITLE
cuda out of memory

### ISSUE THREAD

**Issue by pengluxy** [zhuye98/ICL#2]
Hello author, this paper you wrote is very inspiring! Thank you and your team. But when I reproduce the thesis, there is always insufficient graphics card memory. I am very confused. My GPU has 12G. I have tried various methods, but it still doesn't work. What is the reason?

**Comment by zhuye98** [comment]
Hi pengluxy, this problem may occur when the GPU memory is too small. It is recommended that the GPU memory is at least larger than 32G to train the model.

**Comment by pengluxy** [comment]
okok! thanks a lot!
