### ISSUE TITLE
可视化

### ISSUE THREAD

**Issue by xiaoxiaoma111** [zhuye98/ICL#4]
你好，ACDC数据集和BraTS数据集可视化是怎么实现的呀，可以分享一下嘛

**Comment by zhuye98** [comment]
Hello, for 2D segmentation visualization, you can refer to 'Mask_RCNN/mrcnn/visualize.py'. For 3D segmentation visualization, I personally use ITK-SNAP to export the surface mesh of the segmentation mask (Segmentation -> Export as Surface Mesh...) and then visualize the surface mesh with 3D Slicer.
