### ISSUE TITLE
Inquiry about access to dataset.

### ISSUE THREAD

**Issue by faladawani** [zhuye98/ICL#5]
Hello Zhuye,
I hope this message finds you well.
I'm interested in your methodology and when I tried to run the code, I couldn't installed the ACDC dataset through Baidu! Do you have any alternative way to access the data from the united Kingdom?

Thank you

**Comment by zhuye98** [comment]
Hi faldawani, thank you for your attention. I am not sure if I can directly share the data with you, but you can download the ACDC dataset from this [https://www.creatis.insa-lyon.fr/Challenge/acdc/databases.html](url), and follow the easy pre-processing mentioned in [https://arxiv.org/pdf/2112.04894](url), just resizing and intensity rescaling.

**Comment by faladawani** [comment]
Ok! Thank you.

**Comment by faladawani** [comment]
Thank you.
